# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web1', '0001_initial'),
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.Eventos', verbose_name='Evento'),
        ),
    ]
