# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 11:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('PG', 'Publico General'), ('NB', 'Nivel Basico'), ('NI', 'Nivel Intermedio'), ('NA', 'Nivel Avanzado'), ('PRO', 'Profesional')], max_length=45, verbose_name='Audience')),
                ('description', models.TextField(verbose_name='Description')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('skill_level', models.PositiveIntegerField(verbose_name='Skill Level')),
                ('speaker_information', models.TextField(verbose_name='Speaker Information')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
                ('places', models.CharField(max_length=250, null=True, verbose_name='Places')),
                ('days', models.DateTimeField(null=True, verbose_name='Event Start')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', unique=True)),
                ('date_start', models.DateTimeField(null=True, verbose_name='Start Date')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('published', models.BooleanField(default=False, verbose_name='Published')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='SpeechResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.FileField(upload_to='recursos/')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='actividades.Speech')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Taller', 'Taller'), ('Charla', 'Charla'), ('Dialogo', 'Dialogo')], max_length=45, verbose_name='Name')),
                ('icons', models.CharField(choices=[('/static/img/talleres.png', 'T'), ('/static/img/charlas.png', 'CH'), ('/static/img/dialogos.png', 'D')], max_length=45, verbose_name='Icons')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='speech',
            name='speech_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.SpeechType', verbose_name='Speech Type'),
        ),
        migrations.AddField(
            model_name='speech',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Topic', verbose_name='Topic'),
        ),
        migrations.AddField(
            model_name='speech',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speechs', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
