# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='Apellido')),
                ('institution', models.CharField(blank=True, max_length=12, verbose_name='Instituci\xf3n')),
                ('alimentary_restriction', models.TextField(null=True, verbose_name='Restrinci\xf3n Alimentaria')),
                ('born_date', models.DateField(null=True, verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9, verbose_name='Genero')),
                ('health_consideration', models.TextField(null=True, verbose_name='Condiciones de Salud')),
                ('identification', models.CharField(max_length=12, null=True, verbose_name='Identificaci\xf3n')),
                ('nationality', models.CharField(blank=True, max_length=12, verbose_name='Nacionalidad')),
                ('snore', models.BooleanField(default=False, verbose_name='\xbfRonca?')),
                ('enrolled', models.BooleanField(default=False, verbose_name='\xbfMatriculado?')),
                ('entry_country', models.IntegerField(null=True, verbose_name='Entradas del Pa\xeds')),
                ('out_country', models.IntegerField(null=True, verbose_name='Salidas del Pa\xeds')),
                ('entry_port', models.CharField(max_length=100, null=True, verbose_name='Puerto de Entrada')),
                ('out_port', models.CharField(max_length=100, null=True, verbose_name='Puerto de Salida')),
                ('entry_country_date', models.DateField(null=True, verbose_name='Fecha de Entrada al pa\xeds')),
                ('out_country_date', models.DateField(null=True, verbose_name='Fecha de Salida del pa\xeds')),
                ('letter', models.TextField(null=True, verbose_name='Carta Migratoria')),
                ('invitation_file', models.BooleanField(default=False, verbose_name='\xbfEmail de Invitaci\xf3n?')),
                ('diploma', models.BooleanField(default=False, verbose_name='\xbfEmail de Diploma?')),
            ],
        ),
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(choices=[('PG', 'P\xfablico General'), ('NB', 'Nivel Basico'), ('NI', 'Nivel Intermedio'), ('NA', 'Nivel Avanzado'), ('PRO', 'Profesional')], max_length=45, verbose_name='P\xfablico')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('notes', models.TextField(verbose_name='Notas')),
                ('skill_level', models.PositiveIntegerField(verbose_name='Nivel de Habilidad')),
                ('speaker_information', models.TextField(verbose_name='Informaci\xf3n del Autor')),
                ('title', models.CharField(max_length=250, verbose_name='T\xedtulo')),
                ('places', models.CharField(max_length=250, null=True, verbose_name='Lugares')),
                ('activity_start', models.DateTimeField(null=True, verbose_name='Fecha del Evento')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado')),
                ('published', models.BooleanField(default=False, verbose_name='\xbfPublicado?')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='SpeechResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.FileField(upload_to='recursos/')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recursos', to='actividades.Speech')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speechs_resource_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Talleres', 'Talleres'), ('Charlas', 'Charlas'), ('Di\xe1logos', 'Di\xe1logos')], max_length=45, verbose_name='Nombre')),
                ('icons', models.CharField(choices=[('/static/img/talleres.png', 'Talleres'), ('/static/img/charlas.png', 'Charlas'), ('/static/img/dialogos.png', 'Di\xe1logos')], max_length=45, verbose_name='Iconos')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', unique=True)),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speechs_type_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('description', models.TextField(verbose_name='Descripci\xf3n')),
                ('slug', models.SlugField(help_text='Generador de url, se recomienda no modificar', unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to='sites.Site', verbose_name='Sitios')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.AddField(
            model_name='speech',
            name='speech_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.SpeechType', verbose_name='Tipo de Actividad'),
        ),
        migrations.AddField(
            model_name='speech',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Topic', verbose_name='Tema'),
        ),
        migrations.AddField(
            model_name='speech',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speechs_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='forum_user_profile',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='profile_speech_likes', to='actividades.Speech'),
        ),
        migrations.AddField(
            model_name='forum_user_profile',
            name='matriculatedspeechs',
            field=models.ManyToManyField(blank=True, to='actividades.Speech'),
        ),
        migrations.AddField(
            model_name='forum_user_profile',
            name='sites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
        ),
        migrations.AddField(
            model_name='forum_user_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
