# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 13:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speech',
            name='date_start',
        ),
        migrations.RemoveField(
            model_name='speech',
            name='days',
        ),
        migrations.AddField(
            model_name='speech',
            name='activity_start',
            field=models.DateTimeField(null=True, verbose_name='Fecha del Evento'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='audience',
            field=models.CharField(choices=[('PG', 'P\xfablico General'), ('NB', 'Nivel Basico'), ('NI', 'Nivel Intermedio'), ('NA', 'Nivel Avanzado'), ('PRO', 'Profesional')], max_length=45, verbose_name='P\xfablico'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='description',
            field=models.TextField(verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='notes',
            field=models.TextField(verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='places',
            field=models.CharField(max_length=250, null=True, verbose_name='Lugares'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='published',
            field=models.BooleanField(default=False, verbose_name='\xbfPublicado?'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='skill_level',
            field=models.PositiveIntegerField(verbose_name='Nivel de Habilidad'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='slug',
            field=models.SlugField(help_text='Generador de url, se recomienda no modificar', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='speech',
            name='speaker_information',
            field=models.TextField(verbose_name='Informaci\xf3n del Autor'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='speech_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.SpeechType', verbose_name='Tipo de Actividad'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='title',
            field=models.CharField(max_length=250, verbose_name='T\xedtulo'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actividades.Topic', verbose_name='Tema'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speechs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='speechtype',
            name='icons',
            field=models.CharField(choices=[('/static/img/talleres.png', 'Talleres'), ('/static/img/charlas.png', 'Charlas'), ('/static/img/dialogos.png', 'Di\xe1logos')], max_length=45, verbose_name='Iconos'),
        ),
        migrations.AlterField(
            model_name='speechtype',
            name='name',
            field=models.CharField(choices=[('Talleres', 'Talleres'), ('Charlas', 'Charlas'), ('Di\xe1logos', 'Di\xe1logos')], max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creado'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.TextField(verbose_name='Descripci\xf3n'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=45, unique=True, verbose_name='Nombre'),
        ),
    ]
