# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum_user_profile',
            name='sites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speech',
            name='sites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speechresource',
            name='sites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='speechtype',
            name='sites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
    ]
