# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_auto_20170301_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_user_profile',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9, verbose_name='Genero'),
        ),
    ]
