# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0003_auto_20170211_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_user_profile',
            name='born_date',
            field=models.DateField(blank=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='forum_user_profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9, verbose_name='Genero'),
        ),
        migrations.AlterField(
            model_name='forum_user_profile',
            name='institution',
            field=models.CharField(blank=True, max_length=12, verbose_name='Instituci\xf3n'),
        ),
        migrations.AlterField(
            model_name='forum_user_profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='forum_user_profile',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='forum_user_profile',
            name='nationality',
            field=models.CharField(blank=True, max_length=12, verbose_name='Nacionalidad'),
        ),
    ]
