# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 11:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('actividades', '0003_auto_20170215_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum_User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('institution', models.CharField(max_length=12, verbose_name='Instituci\xf3n')),
                ('alimentary_restriction', models.TextField(null=True, verbose_name='Restrinci\xf3n Alimentaria')),
                ('born_date', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('health_consideration', models.TextField(null=True, verbose_name='Condiciones de Salud')),
                ('identification', models.CharField(max_length=12, null=True, verbose_name='Identificaci\xf3n')),
                ('nationality', models.CharField(max_length=12, verbose_name='Nacionalidad')),
                ('snore', models.BooleanField(default=False, verbose_name='\xbfRonca?')),
                ('enrolled', models.BooleanField(default=False, verbose_name='\xbfMatriculado?')),
                ('entry_country', models.IntegerField(null=True, verbose_name='Entradas del Pa\xeds')),
                ('out_country', models.IntegerField(null=True, verbose_name='Salidas del Pa\xeds')),
                ('entry_port', models.CharField(max_length=100, null=True, verbose_name='Puerto de Entrada')),
                ('out_port', models.CharField(max_length=100, null=True, verbose_name='Puerto de Salida')),
                ('entry_country_date', models.DateField(null=True, verbose_name='Fecha de Entrada al pa\xeds')),
                ('out_country_date', models.DateField(null=True, verbose_name='Fecha de Salida del pa\xeds')),
                ('letter', models.TextField(null=True, verbose_name='Carta Migratoria')),
                ('invitation_file', models.BooleanField(default=False, verbose_name='\xbfEmail de Invitaci\xf3n?')),
                ('diploma', models.BooleanField(default=False, verbose_name='\xbfEmail de Diploma?')),
                ('likes', models.ManyToManyField(blank=True, related_name='profile_speech_likes', to='actividades.Speech')),
                ('matriculatedspeechs', models.ManyToManyField(blank=True, to='actividades.Speech')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
