# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_forum_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speechtype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
