# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0004_auto_20170213_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum_user_profile',
            name='born_date',
            field=models.DateField(null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
