# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('actividades', '0006_auto_20170219_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='sites',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
    ]
