# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0007_topic_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='sites',
            field=models.CharField(max_length=255),
        ),
    ]
