# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0008_auto_20170219_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=45, verbose_name='Nombre'),
        ),
    ]
