# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-08 08:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mozilla_subvention_description', models.TextField(verbose_name='Mozilla Descripci\xf3n Propuesta')),
                ('payed', models.BooleanField(default=False, verbose_name='\xbfPagado?')),
                ('not_registered', models.BooleanField(default=False, verbose_name='No aprobado')),
                ('registered', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('subvention_request', models.BooleanField(default=False, verbose_name='\xbfPropuesta Enviada?')),
                ('sites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
