# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 02:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='enlaces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_social', models.CharField(choices=[('Facebook', 'Facebook'), ('Twitter', 'Twitter')], max_length=8, verbose_name='Red social')),
                ('direccion', models.URLField(verbose_name='Direccion')),
                ('sites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios')),
            ],
        ),
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255, verbose_name='Nombre Evento')),
                ('date_start', models.DateField(blank=True, verbose_name='Fecha de inicio')),
                ('date_end', models.DateField(blank=True, verbose_name='Fecha Final')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pa\xeds')),
                ('places', models.CharField(blank=True, max_length=100, verbose_name='Lugar')),
                ('payed', models.BooleanField(default='False')),
            ],
        ),
        migrations.CreateModel(
            name='Patrocinadores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('web', models.URLField(verbose_name='Web')),
                ('logo', models.ImageField(upload_to='logos/', verbose_name='logo')),
                ('sites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nombre')),
                ('LastName', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('country', models.CharField(max_length=60, verbose_name='Pa\xeds')),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=9, verbose_name='Genero')),
                ('identification', models.CharField(max_length=12, null=True, verbose_name='Identificaci\xf3n')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='WebBuilder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WebLogo', models.ImageField(upload_to='paginas/logos/', verbose_name='Logo')),
                ('banner', models.ImageField(upload_to='paginas/banner/', verbose_name='Banner')),
                ('slogan', models.CharField(max_length=100, verbose_name='Slogan')),
                ('sites', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios')),
            ],
        ),
        migrations.AddField(
            model_name='eventos',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web1.Profile', verbose_name='Perfil'),
        ),
        migrations.AddField(
            model_name='eventos',
            name='sites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
        ),
    ]
