# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('web1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sites',
        ),
        migrations.AddField(
            model_name='eventos',
            name='sites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
    ]
