# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-26 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_auto_20170226_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventos',
            name='title',
        ),
    ]
