# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_patrocinadores_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinadores',
            name='sites',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
        ),
    ]
