# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('web1', '0002_profile_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrocinadores',
            name='sites',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
    ]
