# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 07:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0003_auto_20170301_0228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinadores',
            name='sites',
        ),
    ]
