# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 07:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_remove_patrocinadores_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patrocinadores',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
