# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0004_pagina_web_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina_web',
            name='sites',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
        ),
    ]
