# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('web1', '0006_auto_20170207_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='sites',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enlaces',
            name='sites',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patrocinadores',
            name='sites',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
        ),
    ]
