# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 02:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('web1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('camisetas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirtstyle',
            name='eventos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilos_camisetas', to='web1.Eventos'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camisetas.TshirtStyle', verbose_name='Estilo'),
        ),
        migrations.AddField(
            model_name='tshirt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
