# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('camisetas', '0002_auto_20170210_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='tshirt',
            name='sites',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='sites.Site', verbose_name='Sitios'),
            preserve_default=False,
        ),
    ]
