# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-10 03:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0004_auto_20170210_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tshirtstyle',
            name='eventos',
        ),
    ]
