# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camisetas', '0007_auto_20170301_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img1',
            field=models.ImageField(upload_to='paginas/Tshirt/', verbose_name='Imagen 1'),
        ),
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img2',
            field=models.ImageField(upload_to='paginas/Tshirt/', verbose_name='Imagen 2'),
        ),
        migrations.AlterField(
            model_name='tshirtstyle',
            name='img3',
            field=models.ImageField(upload_to='paginas/Tshirt/', verbose_name='Imagen 3'),
        ),
    ]
